// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: service.proto

#include "service.pb.h"
#include "service.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>
#include <grpcpp/ports_def.inc>

static const char* AService_method_names[] = {
  "/AService/CallService",
};

std::unique_ptr< AService::Stub> AService::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< AService::Stub> stub(new AService::Stub(channel, options));
  return stub;
}

AService::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_CallService_(AService_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status AService::Stub::CallService(::grpc::ClientContext* context, const ::Request& request, ::Response* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Request, ::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_CallService_, context, request, response);
}

void AService::Stub::async::CallService(::grpc::ClientContext* context, const ::Request* request, ::Response* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Request, ::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallService_, context, request, response, std::move(f));
}

void AService::Stub::async::CallService(::grpc::ClientContext* context, const ::Request* request, ::Response* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_CallService_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Response>* AService::Stub::PrepareAsyncCallServiceRaw(::grpc::ClientContext* context, const ::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Response, ::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_CallService_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Response>* AService::Stub::AsyncCallServiceRaw(::grpc::ClientContext* context, const ::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncCallServiceRaw(context, request, cq);
  result->StartCall();
  return result;
}

AService::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      AService_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< AService::Service, ::Request, ::Response, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](AService::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Request* req,
             ::Response* resp) {
               return service->CallService(ctx, req, resp);
             }, this)));
}

AService::Service::~Service() {
}

::grpc::Status AService::Service::CallService(::grpc::ServerContext* context, const ::Request* request, ::Response* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


